#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-RcppArmadillo
Version  : 0.10.4.0.0
Release  : 124
URL      : https://cran.r-project.org/src/contrib/RcppArmadillo_0.10.4.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RcppArmadillo_0.10.4.0.0.tar.gz
Summary  : 'Rcpp' Integration for the 'Armadillo' Templated Linear Algebra
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0+
Requires: R-RcppArmadillo-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: armadillo
BuildRequires : R-Rcpp
BuildRequires : armadillo
BuildRequires : buildreq-R
BuildRequires : openblas

%description
Sanderson) that aims towards a good balance between speed and ease of
 use. Integer, floating point and complex numbers are supported, as
 well as a subset of trigonometric and statistics functions. Various
 matrix decompositions are provided through optional integration with
 LAPACK and ATLAS libraries.  The 'RcppArmadillo' package includes the
 header files from the templated 'Armadillo' library. Thus users do
 not need to install 'Armadillo' itself in order to use
 'RcppArmadillo'. From release 7.800.0 on, 'Armadillo' is licensed
 under Apache License 2; previous releases were under licensed as MPL
 2.0 from version 3.800.0 onwards and LGPL-3 prior to that;
 'RcppArmadillo' (the 'Rcpp' bindings/bridge to Armadillo) is licensed
 under the GNU GPL version 2 or later, as is the rest of 'Rcpp'.
 Armadillo requires a C++11 compiler.

%package lib
Summary: lib components for the R-RcppArmadillo package.
Group: Libraries

%description lib
lib components for the R-RcppArmadillo package.


%prep
%setup -q -c -n RcppArmadillo
cd %{_builddir}/RcppArmadillo

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618412671

%install
export SOURCE_DATE_EPOCH=1618412671
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RcppArmadillo
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RcppArmadillo
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RcppArmadillo
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RcppArmadillo/AUTHORS
/usr/lib64/R/library/RcppArmadillo/CITATION
/usr/lib64/R/library/RcppArmadillo/COPYRIGHTS
/usr/lib64/R/library/RcppArmadillo/DESCRIPTION
/usr/lib64/R/library/RcppArmadillo/INDEX
/usr/lib64/R/library/RcppArmadillo/Meta/Rd.rds
/usr/lib64/R/library/RcppArmadillo/Meta/features.rds
/usr/lib64/R/library/RcppArmadillo/Meta/hsearch.rds
/usr/lib64/R/library/RcppArmadillo/Meta/links.rds
/usr/lib64/R/library/RcppArmadillo/Meta/nsInfo.rds
/usr/lib64/R/library/RcppArmadillo/Meta/package.rds
/usr/lib64/R/library/RcppArmadillo/Meta/vignette.rds
/usr/lib64/R/library/RcppArmadillo/NAMESPACE
/usr/lib64/R/library/RcppArmadillo/NEWS.Rd
/usr/lib64/R/library/RcppArmadillo/R/RcppArmadillo
/usr/lib64/R/library/RcppArmadillo/R/RcppArmadillo.rdb
/usr/lib64/R/library/RcppArmadillo/R/RcppArmadillo.rdx
/usr/lib64/R/library/RcppArmadillo/announce/ANNOUNCE-0.2.0.txt
/usr/lib64/R/library/RcppArmadillo/doc/RcppArmadillo-intro.Rnw
/usr/lib64/R/library/RcppArmadillo/doc/RcppArmadillo-intro.pdf
/usr/lib64/R/library/RcppArmadillo/doc/RcppArmadillo-sparseMatrix.Rnw
/usr/lib64/R/library/RcppArmadillo/doc/RcppArmadillo-sparseMatrix.pdf
/usr/lib64/R/library/RcppArmadillo/doc/index.html
/usr/lib64/R/library/RcppArmadillo/examples/fastLm.r
/usr/lib64/R/library/RcppArmadillo/examples/kalman/FirstKalmanR.R
/usr/lib64/R/library/RcppArmadillo/examples/kalman/Kalman.cpp
/usr/lib64/R/library/RcppArmadillo/examples/kalman/KalmanR.R
/usr/lib64/R/library/RcppArmadillo/examples/kalman/KalmanRimp.R
/usr/lib64/R/library/RcppArmadillo/examples/kalman/benchmark.R
/usr/lib64/R/library/RcppArmadillo/examples/kalman/firstExample.R
/usr/lib64/R/library/RcppArmadillo/examples/kalman/kalmanExample.m
/usr/lib64/R/library/RcppArmadillo/examples/kalman/kalmanM.m
/usr/lib64/R/library/RcppArmadillo/examples/kalman/kalmanfilter.m
/usr/lib64/R/library/RcppArmadillo/examples/kalman/pos.txt
/usr/lib64/R/library/RcppArmadillo/examples/varSimulation.r
/usr/lib64/R/library/RcppArmadillo/help/AnIndex
/usr/lib64/R/library/RcppArmadillo/help/RcppArmadillo.rdb
/usr/lib64/R/library/RcppArmadillo/help/RcppArmadillo.rdx
/usr/lib64/R/library/RcppArmadillo/help/aliases.rds
/usr/lib64/R/library/RcppArmadillo/help/paths.rds
/usr/lib64/R/library/RcppArmadillo/html/00Index.html
/usr/lib64/R/library/RcppArmadillo/html/R.css
/usr/lib64/R/library/RcppArmadillo/include/README
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Alt_R_RNG.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Col_meat.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Col_proto.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Mat_meat.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Mat_proto.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Row_meat.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo/Row_proto.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloAs.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloConfig.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloConfigGenerated.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloConfigGenerated.h.in
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloExtensions/fixprob.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloExtensions/rmultinom.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloExtensions/sample.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloForward.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloSugar.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadilloWrap.h
/usr/lib64/R/library/RcppArmadillo/include/armadillo
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/BaseCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/BaseCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Base_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Base_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Col_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Col_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/CubeToMatOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/CubeToMatOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Cube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Cube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/GenCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/GenCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/GenSpecialiser.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Gen_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Gen_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/GlueCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/GlueCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Glue_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Glue_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/MapMat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/MapMat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Mat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Mat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/OpCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/OpCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Op_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Op_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Proxy.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/ProxyCube.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Row_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/Row_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SizeCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SizeCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SizeMat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SizeMat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpBase_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpBase_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpCol_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpCol_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpGlue_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpGlue_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpMat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpMat_iterators_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpMat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpProxy.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpRow_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpRow_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpSubview_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpSubview_col_list_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpSubview_col_list_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpSubview_iterators_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpSubview_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpToDOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpToDOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpValProxy_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/SpValProxy_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/access.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_cmath.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_config.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_ostream_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_ostream_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_rel_comparators.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_rng.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_rng_cxx11.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_rng_cxx98.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_static_check.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_str.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arma_version.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arrayops_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/auxlib_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/auxlib_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/band_helper.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/compiler_setup_post.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/cond_rel_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/cond_rel_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/config.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/config.hpp.cmake
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/constants.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/constants_old.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/csv_name.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/debug.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_arpack.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_atlas.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_blas.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_hdf5.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_lapack.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/def_superlu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/diagmat_proxy.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/diagview_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/diagview_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/diskio_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/diskio_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/distr_param.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eGlueCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eGlueCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eGlue_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eGlue_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eOpCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eOpCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eglue_core_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eglue_core_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eop_aux.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eop_core_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/eop_core_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fft_engine.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/field_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/field_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_all.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_any.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_approx_equal.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_as_scalar.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_chi2rnd.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_chol.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_clamp.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cond.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_conv.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_conv_to.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cor.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cov.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cross.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cumprod.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_cumsum.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_det.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_diagmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_diagvec.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_diff.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_dot.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eig_gen.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eig_pair.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eig_sym.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eigs_gen.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eigs_sym.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_elem.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eps.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_expmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_eye.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_fft.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_fft2.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_find.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_find_unique.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_flip.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_hess.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_hist.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_histc.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_index_max.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_index_min.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_inplace_strans.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_inplace_trans.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_interp1.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_interp2.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_intersect.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_inv.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_join.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_kmeans.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_kron.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_log_det.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_log_normpdf.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_logmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_lu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_max.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_mean.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_median.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_min.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_misc.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_mvnrnd.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_n_unique.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_nonzeros.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_norm.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_normalise.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_normcdf.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_normpdf.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_numel.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_ones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_orth_null.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_pinv.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_polyfit.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_polyval.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_powmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_princomp.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_prod.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_qr.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_quantile.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_qz.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_randg.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_randi.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_randn.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_randperm.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_randu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_range.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_rank.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_regspace.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_repelem.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_repmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_reshape.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_resize.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_reverse.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_roots.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_schur.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_shift.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_shuffle.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_size.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_solve.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sort.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sort_index.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_speye.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_spones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sprandn.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sprandu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_spsolve.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sqrtmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_stddev.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_strans.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sum.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_svd.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_svds.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_sylvester.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_symmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_toeplitz.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trace.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trans.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trapz.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trig.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trimat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trimat_ind.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trunc_exp.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_trunc_log.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_unique.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_var.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_vectorise.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_wishrnd.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/fn_zeros.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_affmul_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_affmul_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_atan2_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_atan2_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_conv_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_conv_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cor_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cor_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cov_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cov_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cross_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_cross_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_hist_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_hist_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_histc_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_histc_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_hypot_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_hypot_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_intersect_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_intersect_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_join_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_join_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_kron_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_kron_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_max_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_max_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_min_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_min_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_mixed_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_mixed_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_mvnrnd_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_mvnrnd_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_polyfit_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_polyfit_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_polyval_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_polyval_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_quantile_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_quantile_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_relational_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_relational_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_solve_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_solve_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_times_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_times_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_toeplitz_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_toeplitz_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_trapz_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/glue_trapz_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_diag_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_diag_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_full_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_full_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_misc_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/gmm_misc_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/hdf5_misc.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/hdf5_name.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/include_atlas.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/include_hdf5.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/include_superlu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/injector_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/injector_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/memory.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mp_misc.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtGlueCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtGlueCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtGlue_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtGlue_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtOpCube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtOpCube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtSpGlue_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtSpGlue_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtSpOp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mtSpOp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mul_gemm.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mul_gemm_mixed.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mul_gemv.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mul_herk.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/mul_syrk.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_DenseGenMatProd_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_DenseGenMatProd_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_DoubleShiftQR_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_DoubleShiftQR_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_EigsSelect.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_GenEigsSolver_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_GenEigsSolver_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SortEigenvalue.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SparseGenMatProd_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SparseGenMatProd_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SparseGenRealShiftSolve_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SparseGenRealShiftSolve_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SymEigsShiftSolver_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SymEigsShiftSolver_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SymEigsSolver_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_SymEigsSolver_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_TridiagEigen_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_TridiagEigen_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_UpperHessenbergEigen_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_UpperHessenbergEigen_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_UpperHessenbergQR_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_UpperHessenbergQR_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/newarp_cx_attrib.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_all_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_all_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_any_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_any_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_chi2rnd_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_chi2rnd_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_chol_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_chol_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_clamp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_clamp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cond_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cond_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cor_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cor_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cov_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cov_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cumprod_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cumprod_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cumsum_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cumsum_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cx_scalar_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_cx_scalar_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_det_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_det_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diagmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diagmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diagvec_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diagvec_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diff_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_diff_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_dot_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_dot_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_dotext_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_dotext_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_expmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_expmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_fft_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_fft_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_find_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_find_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_find_unique_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_find_unique_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_flip_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_flip_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_hist_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_hist_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_htrans_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_htrans_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_index_max_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_index_max_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_index_min_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_index_min_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_inv_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_inv_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_log_det_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_log_det_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_logmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_logmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_max_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_max_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_mean_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_mean_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_median_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_median_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_min_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_min_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_misc_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_misc_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_nonzeros_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_nonzeros_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_norm_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_norm_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_normalise_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_normalise_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_orth_null_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_orth_null_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_pinv_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_pinv_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_powmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_powmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_princomp_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_princomp_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_prod_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_prod_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_range_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_range_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_relational_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_relational_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_repelem_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_repelem_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_repmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_repmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_reshape_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_reshape_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_resize_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_resize_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_reverse_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_reverse_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_roots_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_roots_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_shift_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_shift_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_shuffle_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_shuffle_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sort_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sort_index_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sort_index_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sort_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sp_minus_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sp_minus_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sp_plus_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sp_plus_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sqrtmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sqrtmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_stddev_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_stddev_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_strans_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_strans_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sum_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_sum_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_symmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_symmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_toeplitz_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_toeplitz_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_trimat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_trimat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_unique_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_unique_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_var_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_var_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_vectorise_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_vectorise_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_wishrnd_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/op_wishrnd_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_div.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_minus.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_plus.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_relational.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_schur.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_cube_times.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_div.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_minus.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_ostream.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_plus.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_relational.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_schur.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/operator_times.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/podarray_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/podarray_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/promote_type.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/restrictors.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/running_stat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/running_stat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/running_stat_vec_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/running_stat_vec_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/sp_auxlib_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/sp_auxlib_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/span.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spdiagview_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spdiagview_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_join_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_join_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_kron_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_kron_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_max_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_max_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_merge_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_merge_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_min_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_min_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_minus_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_minus_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_plus_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_plus_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_relational_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_relational_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_schur_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_schur_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_times_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spglue_times_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_diagmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_diagmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_htrans_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_htrans_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_max_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_max_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_mean_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_mean_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_min_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_min_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_misc_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_misc_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_norm_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_norm_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_normalise_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_normalise_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_repmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_repmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_reverse_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_reverse_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_strans_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_strans_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_sum_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_sum_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_symmat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_symmat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_trimat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_trimat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_var_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_var_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_vectorise_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/spop_vectorise_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/strip.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_each_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_each_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_slices_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_cube_slices_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_each_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_each_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_elem1_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_elem1_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_elem2_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_elem2_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_field_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_field_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/sympd_helper.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/traits.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/translate_arpack.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/translate_atlas.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/translate_blas.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/translate_lapack.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/translate_superlu.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/trimat_helper.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/typedef_elem.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/typedef_elem_check.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/typedef_mat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/typedef_mat_fixed.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/unwrap.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/unwrap_cube.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/unwrap_spmat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/upgrade_val.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/wall_clock_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/wall_clock_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/xtrans_mat_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/xtrans_mat_meat.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/xvec_htrans_bones.hpp
/usr/lib64/R/library/RcppArmadillo/include/armadillo_bits/xvec_htrans_meat.hpp
/usr/lib64/R/library/RcppArmadillo/skeleton/Makevars
/usr/lib64/R/library/RcppArmadillo/skeleton/Makevars.win
/usr/lib64/R/library/RcppArmadillo/skeleton/rcpparma_hello_world.Rd
/usr/lib64/R/library/RcppArmadillo/skeleton/rcpparma_hello_world.cpp
/usr/lib64/R/library/RcppArmadillo/tests/tinytest.R
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/Rlapack.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/any_as_vec.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/armadillo.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/colrow_as_vec.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/complex.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/cube.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/rmultinom.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/rng.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/sample.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/cpp/sparse.cpp
/usr/lib64/R/library/RcppArmadillo/tinytest/test_Rlapack.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_complex.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_cube.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_fastLm.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_rcpparmadillo.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_rmultinom.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_rng.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_sample.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_scipy2r.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_sparse.R
/usr/lib64/R/library/RcppArmadillo/tinytest/test_sparseConversion.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/RcppArmadillo/libs/RcppArmadillo.so
